baseURL = "https://teamsteamstream.github.io/"
languageCode = "en-us"
title = "Team Steam Stream"
theme = "mainroad"

[Author] # Used in authorbox
  name = "Lars Haulin"
  bio = "Lars is an UU alumn, working as an IT-security specialist in Uppsala. He has been playing CTFs for over 10 year with the top ranked swedish team HackingForSoju."
  #avatar = "img/avatar.png"

[Params]
  subtitle = "A CTF team at Uppsala University"# Subtitle of your site. Used in site header
  description = "This we" # Site description. Used in meta description
  opengraph = true # Enable OpenGraph if true
  twitter_cards = false # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = false # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  post_meta = ["date", "categories", "translations"] # Order of post meta information
  mainSections = ["notes", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "taglist", "categories"]

[markup.goldmark.renderer]
unsafe=true
